lf14sm_home:
    path:     /
    defaults: { _controller: LF14SysMgmtBundle:Default:index }

lf14sm_admin:
  path: /admin/
  defaults: { _controller: LF14SysMgmtBundle:Admin:index }

lf14sm_admin_contacts:
  path: /admin/contacts
  defaults: { _controller: LF14SysMgmtBundle:Contact:list }
  
lf14sm_admin_contact_create:
  path: /admin/contact/create
  defaults: { _controller: LF14SysMgmtBundle:Contact:form, id: null }
  
lf14sm_admin_contact_update:
  path: /admin/contact/update/{id}
  defaults: { _controller: LF14SysMgmtBundle:Contact:form }
  requirements:
    id: \d+
  