parameters:
#    lf14_sys_mgmt.example.class: LF14\SysMgmtBundle\Example

services:
#    lf14_sys_mgmt.example:
#        class: %lf14_sys_mgmt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
